import Head from 'next/head';
import Link from 'next/link';
import dynamic from 'next/dynamic';
// import { useSession } from 'next-auth/client';
import { Button, Flex, Heading, Text } from '@chakra-ui/react';
import { AddIcon } from '@chakra-ui/icons';
import NavBar from '../components/NavBar';
import knex from '../knex';

const ProgressBar = dynamic(() => import('../components/Progress'), { ssr: false });

const Home = ({ categories, user, progress, level }) => {
	// const [session] = useSession();

	return (
		<Flex>
			<Head>
				<title>SKIF Progress App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar categories={categories} />
			<Flex w="100%" justifyContent="center" alignItems="center" flexDirection="column">
				{/* {session && ( */}
				<>
					<Heading>{user[0].name}</Heading>
					<Heading>{user[0].level}</Heading>
					<ProgressBar progress={progress} level={level} levelid={user[0].level_id} />
					<Link href="/training-log">
						<Button leftIcon={<AddIcon />} m={15}>
							Update Progress
						</Button>
					</Link>
				</>
				{/* )} */}
				{/* {!session && <p>Sign in to see your progress</p>} */}
			</Flex>
		</Flex>
	);
};

export default Home;

export const getServerSideProps = async () => {
	// Query
	const data1 = await knex('categories');
	const data2 = await knex('users').join('levels', 'users.level_id', 'levels.levelID');
	const data3 = await knex('users').join('progress', 'users.progress_id', 'progress.ProgressID');
	const data4 = await knex('levels');

	// Send results als props
	const categories = JSON.parse(JSON.stringify(data1));
	const user = JSON.parse(JSON.stringify(data2));
	const progress = JSON.parse(JSON.stringify(data3));
	const level = JSON.parse(JSON.stringify(data4));

	return {
		props: {
			categories,
			user,
			progress,
			level,
		},
	};
};
