import Head from 'next/head';
import Link from 'next/link';
import { useSession } from 'next-auth/client';
import { Box, Button, Flex, Heading, Text, Spinner } from '@chakra-ui/react';
import { ChevronRightIcon } from '@chakra-ui/icons';
import NavBar from '../components/NavBar';
import SignUp from '../components/SignUp';
import Auth from '../components/Auth';
import knex from '../knex';

const Home = ({ categories, users, levels }) => {
	const [session, loading] = useSession();
	const thisUser = session ? users.filter(user => user.email === session.user.email)[0] : null;
	// console.log(thisUser);

	return (
		<Flex h="100vh">
			<Head>
				<title>SKIF Progress App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar categories={categories} />
			<Flex
				w="calc(100vw - 2vh - 60px)"
				h="98vh"
				justifyContent="center"
				alignItems="center"
				flexDirection="column"
				pos="absolute"
				top="2vh"
				left="calc(60px + 2vh)"
				p="1em">
				<Heading as="h1" fontSize={['1.5rem', '2rem', '2.5rem']} mb={10} color="teal.600">
					SKIF Progress App
				</Heading>
				{loading && <Spinner />}
				{session && (
					<>
						{thisUser.name === null || thisUser.level_id === null ? (
							<>
								<Text textAlign="center">
									Thank you for using the SKIF Progress App! <br />
									It seems like you don't have an account yet. Register here.
								</Text>
								<SignUp user={thisUser} levels={levels} />
							</>
						) : (
							<>
								<Heading fontSize={['1.2rem', '1.7rem', '2rem']} mb={10}>
									Hi, {thisUser.name}! Welcome back.
								</Heading>
								<Button leftIcon={<ChevronRightIcon />}>
									<Link href={`/user/${thisUser.id}`}>
										<a>Progress</a>
									</Link>
								</Button>
							</>
						)}
					</>
				)}
				{!session && !loading && (
					<>
						<Text textAlign="center" mb={10} w="50%">
							Welcome to the Skif progress app! In this application you will be able
							to search an excercise you want to train by your own. It is also
							possible to keep your progress of your karate journey after creating an
							account.
						</Text>
						<Text textAlign="center" mb={5} w="60%">
							You're not signed in. Please sign in from the link below to be able to
							save you progress.
						</Text>
						<Box>
							<Auth />
						</Box>
					</>
				)}
			</Flex>
		</Flex>
	);
};

export default Home;

export const getServerSideProps = async () => {
	// Query
	const data1 = await knex('categories');
	const data2 = await knex('users');
	const data3 = await knex('levels');

	// Send results als props
	const categories = JSON.parse(JSON.stringify(data1));
	const users = JSON.parse(JSON.stringify(data2));
	const levels = JSON.parse(JSON.stringify(data3));
	// console.log(levels);

	return {
		props: {
			// session,
			categories,
			users,
			levels,
		},
	};
};
